<?php
	$propertyPricesArr 		= $propertyObj->fun_getPropertyPricesArr($property_id);
	$propertyCurrencyId		= $propertyObj->fun_findPropertyCurrencyCode($property_id);
	$propertyCurrencySymbol	= $propertyObj->fun_findPropertyCurrencySymbol($property_id, '');
	$currencyRateArr		= $propertyObj->fun_findPropertyCurrencyRate();

//print_r($currencyRateArr);

?>

<script language="javascript">
	var req = ajaxFunction();
	//************ NOTE: DO NOT EDIT THIS FILE MANUALLY *************
	var gh_rates = new Object;
	gh_rates["USD"]=<?php echo $currencyRateArr['USD']; ?>;
	gh_rates["GBP"]=<?php echo $currencyRateArr['GBP']; ?>;
	gh_rates["EUR"]=<?php echo $currencyRateArr['EUR']; ?>;
	//************ NOTE: DO NOT EDIT THIS FILE MANUALLY *************

	function getCurrSymbol(lscurr) {
		var lsOut;
		//alert('getCurrSymbol()');
		switch(lscurr) {
			case "USD": lsOut = "$"; break;
			case "EUR": lsOut = "&euro;"; break;
			case "GBP": lsOut = "&pound;"; break;
		}
		return lsOut;
	}

	function roundprice(rprice, rbpence) { 
		//rprice [the full price to be rounded]
		//rbpence flag to specify to round to pence(3.99) or to pound(3)[  1=pence 0=pounds ]
		//rprice=222.5; rbpence=1;
		
		//alert('roundpence() rprice='+rprice + ' rbpence='+rbpence);
		var mystr = rprice.toString();
		var mypos=mystr.indexOf(".");
		//alert('roundpence() mypos='+mypos);
		if (mypos==-1)  {
			retval=mystr;
			//Put comma in to represent thousand separator - what a pain!!
			//alert('leaving here');
			
			
			if (rbpence==1)   {
				//No decimal place, so add the .00
				retval=mystr+'.00'
			}
		} else  {	
		
			if (rbpence==1)  {
				//Add a ZERO if only one number after the decimal place
				//Get the bit before the decimal place
				var after = mystr.slice(mypos+1);
				//alert('a) after='+after);
				if (after.length==1)  {  //dp+1digit==2
					after=after+'0';
					//alert('b) after='+after);
				} else  {
					//Get 3 digits (if they exist) so we can round properly
					//alert('after=' + after);
					
					if (after.length > 2 )  {
						after=after.slice(0,2) + '.' + after.slice(2,3);
						//Rounds to 2 dp
						after=Math.round(after);
					}
					//alert('after slice=' + after);
				}
				retval=mystr.slice(0,mypos) + '.' + after;
			} else  {
				//Just return the bit before the decimal place
				//retval=mystr.slice(0,mypos);
				retval=Math.round(mystr)
			}
			
			
		}
		//alert('roundpence() retval='+retval);
		return addCommas(retval);
	}

	function addCommas(nStr)
	{
		nStr += '';
		x = nStr.split('.');
		x1 = x[0];
		x2 = x.length > 1 ? '.' + x[1] : '';
		var rgx = /(\d+)(\d{3})/;
		while (rgx.test(x1)) {
			x1 = x1.replace(rgx, '$1' + ',' + '$2');
		}
		return x1 + x2;
	}


	//Save their currency preference
	function save_preferred_ccy(curcode) {
		req.open('get', 'setUserCurrency.php?curcode=' + curcode); 
		req.send(null); 
	}


	function convertCurrency(to_ccy) { 

		var cntPriceArr	= <?php echo count($propertyPricesArr); ?>;
		if(parseInt(cntPriceArr) > 0) {
			for (var i = 0; i < cntPriceArr; i++)  {
				//Get Amounts
				var currencyValueId1 = document.getElementById('price_currency_value_id1'+i);
				var currencyValueId2 = document.getElementById('price_currency_value_id2'+i);
				var currencyValueId3 = document.getElementById('price_currency_value_id3'+i);


				var currencySymbolId1 = document.getElementById('price_currency_symbol_id1'+i);
				var currencySymbolId2 = document.getElementById('price_currency_symbol_id2'+i);
				var currencySymbolId3 = document.getElementById('price_currency_symbol_id3'+i);
				switch(to_ccy) {
					case 'USD':
						convertedCurrencyValue1 = roundprice(document.getElementById('price_rate_usd_id1'+i).value,0);
						convertedCurrencyValue2 = roundprice(document.getElementById('price_rate_usd_id2'+i).value,0);
						convertedCurrencyValue3 = roundprice(document.getElementById('price_rate_usd_id3'+i).value,0);
					break;
					case 'GBP':
						convertedCurrencyValue1 = roundprice(document.getElementById('price_rate_gbp_id1'+i).value,0);
						convertedCurrencyValue2 = roundprice(document.getElementById('price_rate_gbp_id2'+i).value,0);
						convertedCurrencyValue3 = roundprice(document.getElementById('price_rate_gbp_id3'+i).value,0);
					break;
					case 'EUR':
						convertedCurrencyValue1 = roundprice(document.getElementById('price_rate_eur_id1'+i).value,0);
						convertedCurrencyValue2 = roundprice(document.getElementById('price_rate_eur_id2'+i).value,0);
						convertedCurrencyValue3 = roundprice(document.getElementById('price_rate_eur_id3'+i).value,0);
					break;
				}

				currencySymbolId1.innerHTML = getCurrSymbol(to_ccy);
				currencySymbolId2.innerHTML = getCurrSymbol(to_ccy);
				currencySymbolId3.innerHTML = getCurrSymbol(to_ccy);

				currencyValueId1.innerHTML = convertedCurrencyValue1;
				currencyValueId2.innerHTML = convertedCurrencyValue2;
				currencyValueId3.innerHTML = convertedCurrencyValue3;
			}
		}

		//Save their currency preference
		save_preferred_ccy(to_ccy);
		return true;
	} 
	
</script>

<table border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td valign="top">
            <ul>
                <li class="TabLeft">&nbsp;</li>
                <li class="SummaryTabUS"><a href="javascript:showSection(1);" title="Summary"><img src="images/Summary-US.gif" alt="Summary" border="0" /></a></li>
                <li class="PricesTabS"><a href="javascript:showSection(2);" title="Prices"><img src="images/Prices-S.gif" alt="Prices" border="0" /></a></li>
                <li class="AvailabilityTabUS"><a href="javascript:showSection(3);" title="Availability"><img src="images/Availabilty-US.gif" alt="Availability" border="0" /></a></li>
                <li class="AccomoFacilitiesTabUS"><a href="javascript:showSection(4);" title="AccomoFacilities"><img src="images/Acco-n-Facilities-US.gif" alt="AccomoFacilities" border="0" /></a></li>
                <li class="LocationTabUS"><a href="javascript:showSection(5);" title="Location"><img src="images/Location-US.gif" alt="Location" border="0" /></a></li>
                <li class="ReviewsTabUS"><a href="javascript:showSection(6);" title="Reviews"><img src="images/Reviews-US.gif" alt="Reviews" border="0" /><span class="VPTxt-UNS">(<?php if(is_array($propertyObj->fun_getPropertyReviewsArr($property_id))) {echo count($propertyObj->fun_getPropertyReviewsArr($property_id));} else { echo "0";} ?>)</span></a></li>
                <li class="AboutAreaTabUS"><a href="javascript:showSection(7);" title="AboutArea"><img src="images/About-Area-US.gif" alt="AboutArea" border="0" /></a></li>
                <li class="ContactOwnerTabUS"><a href="javascript:showSection(8);" title="ContactOwner"><img src="images/Contact-owner-US.gif" alt="ContactOwner" border="0" /></a></li>
                <li class="TabRight">&nbsp;</li>
            </ul>
        </td>
    </tr>
    <tr><td><img src="images/tab-top.gif" alt="Image" /></td></tr>
    <tr>
        <td valign="top" class="Tab-Bg">
            <!-- property prices inner tabs : start here --> 
            <table width="888" cellpadding="0" cellspacing="0" class="font12">
                <tr>
                    <td><img src="images/spacer.gif" alt="Image" width="24" height="20" /></td>
                    <td>
                        <table width="100%" cellpadding="0" cellspacing="0">
                            <tr><td class="pad-btm15"><div class="blackHeadtab">Prices</div></td></tr>
                            <tr>
                                <td colspan="2" align="left" valign="top">
                                    <p class="FloatLft"><span class="black">Rental rates</span>: Per property   &nbsp;&nbsp;<span class="black">Quoted in:</span> <?php echo $property_currency_symbol." ".ucwords($propertyObj->fun_findPropertyCurrencyName($property_id));?></p>
                                    <div align="right" class="font12 FloatRgt">
                                    <table border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td class="pad-rgt10">See approximate prices in</td>
                                            <td>
                                                <select name="txtCurrencyType" id="txtCurrencyType" class="PropertyListingCurrency" style="width:190px;" onchange="convertCurrency(this.value);">
                                                <?php 
                                                    $propertyObj->fun_getCurrenciesOptionsListWithCodeSymbl($users_currency_code);
                                                ?>
                                                </select>
                                            </td>
                                        </tr>
                                    </table>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td align="left" valign="top" class="pad-top12">
                                    <table width="843" border="0" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td class="PricesHeadV">Date from </td>
                                            <td class="PricesHeadV">Date to</td>
                                            <td align="center" class="PricesHeadV">Per week </td>
                                            <td align="center" class="PricesHeadV">Per midweek night </td>
                                            <td align="center" class="PricesHeadV">Per weekend night </td>
                                            <td align="center" class="PricesHeadV">Minimum stay</td>
                                        </tr>

										<?php 
                                        if(count($propertyPricesArr) > 0){
                                            for($i=0; $i<count($propertyPricesArr); $i++){

                                                $property_price_id		= $propertyPricesArr[$i]['id'];
                                                $dateFrom 				= date('F j, Y', strtotime($propertyPricesArr[$i]['date_from']));
                                                $dateTo 				= date('F j, Y', strtotime($propertyPricesArr[$i]['date_to']));
                                                $minStay 				= $propertyPricesArr[$i]['min_stay'];
                                                $stayType 				= $propertyPricesArr[$i]['min_stay_type'];
                                                if((int)$minStay > 1) {
                                                    $strMinStay			= $propertyPricesArr[$i]['min_stay'] ." ".(($stayType == "w") ? "Weeks" : "Nights");
                                                } else {
                                                    $strMinStay			= $propertyPricesArr[$i]['min_stay'] ." ".(($stayType == "w") ? "Week" : "Night");
                                                }


                                                $perWeekPrice 			= $propertyObj->fun_getConvertedCurrency($property_currency_id, $users_currency_id, $propertyPricesArr[$i]['per_week_price']);
                                                $perNightMidweekPrice 	= $propertyObj->fun_getConvertedCurrency($property_currency_id, $users_currency_id, $propertyPricesArr[$i]['per_night_midweek_price']);
                                                $perNightWeekendPrice 	= $propertyObj->fun_getConvertedCurrency($property_currency_id, $users_currency_id, $propertyPricesArr[$i]['per_night_weekend_price']);
                                                $specialOffer 			= $propertyPricesArr[$i]['special_offer'];
												
												?>
                                                <input name="<?php echo "price_rate_usd_1".$i;?>"  id="<?php echo "price_rate_usd_id1".$i;?>" type="hidden" value="<?php echo (($perWeekPrice/$currencyRateArr[$users_currency_code])*$currencyRateArr['USD']); ?>" />
                                                <input name="<?php echo "price_rate_usd_2".$i;?>"  id="<?php echo "price_rate_usd_id2".$i;?>" type="hidden" value="<?php echo (($perNightMidweekPrice/$currencyRateArr[$users_currency_code])*$currencyRateArr['USD']); ?>" />
                                                <input name="<?php echo "price_rate_usd_3".$i;?>"  id="<?php echo "price_rate_usd_id3".$i;?>" type="hidden" value="<?php echo (($perNightWeekendPrice/$currencyRateArr[$users_currency_code])*$currencyRateArr['USD']); ?>" />


                                                <input name="<?php echo "price_rate_gbp_1".$i;?>"  id="<?php echo "price_rate_gbp_id1".$i;?>" type="hidden" value="<?php echo (($perWeekPrice/$currencyRateArr[$users_currency_code])*$currencyRateArr['GBP']); ?>" />
                                                <input name="<?php echo "price_rate_gbp_2".$i;?>"  id="<?php echo "price_rate_gbp_id2".$i;?>" type="hidden" value="<?php echo (($perNightMidweekPrice/$currencyRateArr[$users_currency_code])*$currencyRateArr['GBP']); ?>" />
                                                <input name="<?php echo "price_rate_gbp_3".$i;?>"  id="<?php echo "price_rate_gbp_id3".$i;?>" type="hidden" value="<?php echo (($perNightWeekendPrice/$currencyRateArr[$users_currency_code])*$currencyRateArr['GBP']); ?>" />



                                                <input name="<?php echo "price_rate_eur_1".$i;?>"  id="<?php echo "price_rate_eur_id1".$i;?>" type="hidden" value="<?php echo (($perWeekPrice/$currencyRateArr[$users_currency_code])*$currencyRateArr['EUR']); ?>" />
                                                <input name="<?php echo "price_rate_eur_2".$i;?>"  id="<?php echo "price_rate_eur_id2".$i;?>" type="hidden" value="<?php echo (($perNightMidweekPrice/$currencyRateArr[$users_currency_code])*$currencyRateArr['EUR']); ?>" />
                                                <input name="<?php echo "price_rate_eur_3".$i;?>"  id="<?php echo "price_rate_eur_id3".$i;?>" type="hidden" value="<?php echo (($perNightWeekendPrice/$currencyRateArr[$users_currency_code])*$currencyRateArr['EUR']); ?>" />
												<?php 
                                                if($specialOffer > 0) { 
                                                ?>
                                                <tr id="<?php echo "price_row_id".$property_price_id;?>" >
                                                    <td align="Left" class="pricesSpecialV"><?php echo $dateFrom; ?></td>
                                                    <td align="Left" class="pricesSpecialV"><?php echo $dateTo; ?></td>
                                                    <td align="center" class="pricesSpecialV" id="<?php echo "price_cell_id1".$i;?>"><span id="<?php echo "price_currency_symbol_id1".$i;?>"><?php echo $users_currency_symbol; ?></span><span id="<?php echo "price_currency_value_id1".$i;?>"><?php echo number_format($perWeekPrice); ?></span></td>
                                                    <td align="center" class="pricesSpecialV" id="<?php echo "price_cell_id2".$i;?>"><span id="<?php echo "price_currency_symbol_id2".$i;?>"><?php echo $users_currency_symbol; ?></span><span id="<?php echo "price_currency_value_id2".$i;?>"><?php echo number_format($perNightMidweekPrice); ?></span></td>
                                                    <td align="center" class="pricesSpecialV" id="<?php echo "price_cell_id3".$i;?>"><span id="<?php echo "price_currency_symbol_id3".$i;?>"><?php echo $users_currency_symbol; ?></span><span id="<?php echo "price_currency_value_id3".$i;?>"><?php echo number_format($perNightWeekendPrice); ?></span></td>
                                                    <td align="center" class="pricesSpecialV"><?php echo $strMinStay; ?></td>
                                                </tr>
                                                <?php
                                                } else {
                                                ?>
                                                <tr id="<?php echo "price_row_id".$property_price_id;?>" >
                                                    <td align="Left" class="PricesBlankV"><?php echo $dateFrom; ?></td>
                                                    <td align="Left" class="PricesBlankV"><?php echo $dateTo; ?></td>
                                                    <td align="center" class="PricesBlankV" id="<?php echo "price_cell_id1".$i;?>"><span id="<?php echo "price_currency_symbol_id1".$i;?>"><?php echo $users_currency_symbol; ?></span><span id="<?php echo "price_currency_value_id1".$i;?>"><?php echo number_format($perWeekPrice); ?></span></td>
                                                    <td align="center" class="PricesBlankV" id="<?php echo "price_cell_id2".$i;?>"><span id="<?php echo "price_currency_symbol_id2".$i;?>"><?php echo $users_currency_symbol; ?></span><span id="<?php echo "price_currency_value_id2".$i;?>"><?php echo number_format($perNightMidweekPrice); ?></span></td>
                                                    <td align="center" class="PricesBlankV" id="<?php echo "price_cell_id3".$i;?>"><span id="<?php echo "price_currency_symbol_id3".$i;?>"><?php echo $users_currency_symbol; ?></span><span id="<?php echo "price_currency_value_id3".$i;?>"><?php echo number_format($perNightWeekendPrice); ?></span></td>
                                                    <td align="center" class="PricesBlankV"><?php echo $strMinStay; ?></td>
                                                </tr>
                                                <?php
                                                }
                                            }
                                        }
                                        ?>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td class="pad-btm25 pad-top10">NB: Special deals are indicated in <span style="background-color:#FDC943; color:#BF0000; padding:1px;">RED</span></td>
                            </tr>
                            <tr><td class="owner-headings">Notes</td></tr>
                            <tr>
                                <td><?php echo $propertyObj->fun_getPropertyPriceNotes($property_id); ?></td>
                            </tr>
                        </table>
                    </td>
                    <td><img src="images/spacer.gif" alt="Summary" width="22" height="30" /></td>
                </tr>
            </table>
            <!-- property prices inner tabs : end here --> 
        </td>
    </tr>
    <tr><td><img src="images/tab-bttm.gif" alt="Image" /></td></tr>
</table>