<table width="690" border="0" cellspacing="0" cellpadding="0" class="font12">
    <tr><td class="pad-rgt10"><h1 class="page-headingNew">Terms &amp; Conditions</h1></td></tr>
    <tr>
        <td align="left" valign="top" class="pad-btm20">
            <table width="690" border="0" cellspacing="0" cellpadding="0" class="font12">
                <tr>
                    <td colspan="2" align="left" valign="bottom">
                        <table width="100%" border="0" cellpadding="0" cellspacing="0">
                            <tr>
                                <td align="left" valign="top">
                                    <table width="690" border="0" cellspacing="0" cellpadding="0" class="font12">
                                        <tr><td colspan="2" align="left" valign="bottom" class="height20">&nbsp;</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="font14-darkgrey">Contents of Advertisement</td></tr>
                                        <tr>
                                            <td colspan="2" align="left" valign="top" class=" pad-btm10">
												rentownersvillas.com (Master Cabin  Ltd) accepts and displays advertisements in good faith. The content and accuracy of any advertisement is the sole responsibility of the owner or agent of the property displayed. All advertisements should comply with relevant UK legislation including the Trade Descriptions Act 1968 (which covers false advertising descriptions) and the Consumer Protection Act 1987 (which covers misleading prices). The advertiser agrees to indemnify Master Cabin  against all claims costs arising out of any misleading information in the advertisement. Master Cabin  will make every effort to reproduce faithfully the content of the advertisement as supplied by the owner or agent of the property. We will not, however, be held liable for any loss arising out of any error or omission on our part. Master Cabin  reserves the right to determine the design and layout of advertisements and make changes to the supplied material including text, photographs and videos should we consider it necessary. Master Cabin  will not be held liable for any loss arising out of such changes.
                                            </td>
                                        </tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Copyright</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">In order that Master Cabin  can display your advertisement contents, you confirm that your contents including text, photos and videos is your own original work, is not defamatory and does not infringe any UK laws and that you have the right to reproduce any photos, videos or digital images which you supply to us. You also confirm that you have the consent of anyone who is identifiable in your contribution.<br /></td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">It is the responsibility of the advertiser to ensure they have the right to reproduce any photographs or digital images which they supply to us. The advertiser agrees to indemnify Master Cabin  against all claims costs arising out of any infringement of copyright for such photographs or images. The advertiser grants Master Cabin , free of charge, permission to use the material supplied for marketing and promotional purposes (including public relations material). All digital images produced by Master Cabin  from photographs supplied by advertisers are the property of Master Cabin , and shall not be reproduced without our permission.<br /></td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">This website contains material and software that is owned and licensed to Master Cabin . This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions. Unauthorised use of this website and it&rsquo;s contents may give claim for damages and/or be a criminal offence.</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Site and operational changes</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">Master Cabin  reserves the right to change, suspend or discontinue any aspect of the website and it&rsquo;s services without notice, including the availability of any site features, database, or content, where we have legal, commercial or technical reasons to do so which includes technical reasons experienced by Master Cabin  or on the internet. We may also impose restrictions on our services or restrict access to parts or all of the site for the same reasons.<br /></td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Site unavailability</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">There may be times when the rentownersvillas.com service becomes unavailable as a result of technical difficulties by us or on the internet. We will endeavour to overcome these difficulties as a matter of priority where they are within our control. There may be times, however, when the site becomes unavailable on a scheduled or unscheduled basis and as a result we cannot guarantee continuous access to the site or it&rsquo;s features.</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Liability</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">The information and services included on this site may include inaccuracies or typographical errors. In no event shall Master Cabin  become liable to the advertiser for any special, consequential, incidental or indirect damages, including lost profits, however caused, on any theory of liability in connection with advertising on the rentownersvillas.com site.<br /></td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Suspending, declining or withdrawing a property advertisement</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">Master Cabin  reserves the right to suspend or withdraw a property at any time if we consider the content either incomplete or unsuitable. If a complaint is received about a particular property this may result in the property being removed from the site if the complaint, in our opinion, is substantiated. In this event no refund will be given. If an owner no longer wishes to advertise their property on rentownersvillas.com prior to the end of their subscription period then we require a formal written email request using our &lsquo;Contact us&rsquo; form together with the property ID. In this event no refunds will be given.</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Exchanging properties</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">Each advertisement relates to a particular property and is given a unique reference ID. It is not allowable for an owner to substitute this property for another by way of changing text and images unless prior permission is given by Master Cabin . We reserve the right to immediately suspend a property in such a case.<br /></td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">External links</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">Master Cabin  reserves the right to refuse or remove links or email addresses to external websites that it deems, in it&rsquo;s opinion, to be either inappropriate or acting against the interest of the company and / or it&rsquo;s advertisers. If an advertiser re-instates a removed link or adds a link or email address without prior consent or approval from Master Cabin , we reserve the right to suspend the advert without notice. Master Cabin  also reserves the right to refuse, remove or suspend reciprocated links at any time without notice.</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Email enquiry forms</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">Master Cabin  monitor the use of contact email forms and reserve the right to suppress any enquires we deem not to be genuine availability and booking enquiries by holidaymakers or which constitute unsolicited commercial marketing.</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Changes to prices and conditions</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">Master Cabin  reserves the right to change it&rsquo;s prices and conditions without notice. Any new prices will be applicable immediately for all new adverts and renewals for both new and existing customers.</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Payment information</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">When a new property is added to the site payment is required before the advert will be posted live on the website. All payments must be made online by either credit or debit card through our online card payment provider, WorldPay (part of the Royal Bank of Scotland Group). You can contact us via email using the contact us page or if you wish to contact us by post our contact address is: 9 North Street West, Uppingham, Rutland LE15 9SF.</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Refunds policy</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">Refunds may be given at the discretion of the management.</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class="pad-top5 font14-darkgrey">Company details</td></tr>
                                        <tr><td colspan="2" align="left" valign="top" class=" pad-btm10">Master Cabin  Ltd is a registered company in England and Wales (Registered number: 6510698). Place of registration: Companies House, Cardiff.  Registered office address: 9 North Street West, Uppingham, Rutland LE15 9SF. Contact telephone number: +27 (0) 79 340 2197. Contact email address: <a href="mailto:info@rentownersvillas.com" class="blue-link">info@rentownersvillas.com</a></td></tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
