<div id="tab_menu-1">
    <ul>
        <li><a href="#showSectionOverview" onclick="return showSection(1);" title="Description">Property details</a></li>
		<?php /*?>
        <li><a href="#showSectionPhotos" onclick="return showSection(2);" title="Photos">Photos</a></li>
		<?php */?>
        <li><a href="#showSectionLocation" onclick="return showSection(3);" title="Location">Location</a></li>
        <li><a href="#showSectionAbout" onclick="return showSection(4);" title="Amenities">Amenities</a></li>
        <li><a href="#showSectionCalendar" onclick="return showSection(5);" title="Availability">Availability</a></li>
        <li><a href="#showSectionPrice" onclick="return showSection(6);" title="Prices" class="current">Rates</a></li>
        <li><a href="#showSectionReview" onclick="return showSection(7);" title="Reviews">Reviews</a></li>
		<?php /*?>
        <li style="margin-right:0px; margin-left:6px;"><a href="<?php echo SITE_URL;?>property-owner-profile.php?pid=<?php echo $property_id;?>" title="Owner">Owner profile</a></li>
		<?php */?>
        <li style="margin-right:0px; margin-left:6px;"><a href="#showSectionOwner" onclick="return showSection(8);" title="Owner">Owner profile</a></li>
		<?php
        if($booking_on == true) {
        ?>
        <li><a href="javascript:void(0);" onclick="submitTripDuration('<?php echo $date_from;?>', <?php echo $date_to;?>)" title="Book Now" style="color:#e89c4e;">Book Now</a></li>
        <?php
        }
        ?>
    </ul>
</div>
<h2><strong><?php echo tranText('property_rates'); ?></strong></h2>
<?php
//For price
//shifted to upper page
//	$propertyPricesArr 		= $propertyObj->fun_getPropertyPricesArr($property_id);
//	$propertyCurrencyId		= $propertyObj->fun_findPropertyCurrencyCode($property_id);
//	$propertyCurrencySymbol	= $propertyObj->fun_findPropertyCurrencySymbol($property_id, '');
//	$currencyRateArr		= $propertyObj->fun_findPropertyCurrencyRate();
?>

<script language="javascript">
	var req = ajaxFunction();
	//************ NOTE: DO NOT EDIT THIS FILE MANUALLY *************
	var gh_rates = new Object;
	gh_rates["USD"]=<?php echo $currencyRateArr['USD']; ?>;
	gh_rates["GBP"]=<?php echo $currencyRateArr['GBP']; ?>;
	gh_rates["EUR"]=<?php echo $currencyRateArr['EUR']; ?>;
	//************ NOTE: DO NOT EDIT THIS FILE MANUALLY *************

	function getCurrSymbol(lscurr) {
		var lsOut;
		//alert('getCurrSymbol()');
		switch(lscurr) {
			case "USD": lsOut = "$"; break;
			case "EUR": lsOut = "&euro;"; break;
			case "GBP": lsOut = "&pound;"; break;
		}
		return lsOut;
	}

	function roundprice(rprice, rbpence) { 
		//rprice [the full price to be rounded]
		//rbpence flag to specify to round to pence(3.99) or to pound(3)[  1=pence 0=pounds ]
		//rprice=222.5; rbpence=1;
		
		//alert('roundpence() rprice='+rprice + ' rbpence='+rbpence);
		var mystr = rprice.toString();
		var mypos=mystr.indexOf(".");
		//alert('roundpence() mypos='+mypos);
		if (mypos==-1)  {
			retval=mystr;
			//Put comma in to represent thousand separator - what a pain!!
			//alert('leaving here');
			
			
			if (rbpence==1)   {
				//No decimal place, so add the .00
				retval=mystr+'.00'
			}
		} else  {	
		
			if (rbpence==1)  {
				//Add a ZERO if only one number after the decimal place
				//Get the bit before the decimal place
				var after = mystr.slice(mypos+1);
				//alert('a) after='+after);
				if (after.length==1)  {  //dp+1digit==2
					after=after+'0';
					//alert('b) after='+after);
				} else  {
					//Get 3 digits (if they exist) so we can round properly
					//alert('after=' + after);
					
					if (after.length > 2 )  {
						after=after.slice(0,2) + '.' + after.slice(2,3);
						//Rounds to 2 dp
						after=Math.round(after);
					}
					//alert('after slice=' + after);
				}
				retval=mystr.slice(0,mypos) + '.' + after;
			} else  {
				//Just return the bit before the decimal place
				//retval=mystr.slice(0,mypos);
				retval=Math.round(mystr)
			}
			
			
		}
		//alert('roundpence() retval='+retval);
		return addCommas(retval);
	}

	function addCommas(nStr)
	{
		nStr += '';
		x = nStr.split('.');
		x1 = x[0];
		x2 = x.length > 1 ? '.' + x[1] : '';
		var rgx = /(\d+)(\d{3})/;
		while (rgx.test(x1)) {
			x1 = x1.replace(rgx, '$1' + ',' + '$2');
		}
		return x1 + x2;
	}


	//Save their currency preference
	function save_preferred_ccy(curcode) {
		req.open('get', '<?php echo SITE_URL;?>setUserCurrency.php?curcode=' + curcode); 
		req.send(null); 
	}


	function convertCurrency(to_ccy) { 

		var cntPriceArr	= <?php echo count($propertyPricesArr); ?>;
		
		if(parseInt(cntPriceArr) > 0) {
			for (var i = 0; i < cntPriceArr; i++)  {
				//Get Amounts
				var currencyValueId0 = document.getElementById('price_currency_value_id0'+i);
				var currencyValueId1 = document.getElementById('price_currency_value_id1'+i);
				var currencyValueId2 = document.getElementById('price_currency_value_id2'+i);
//				var currencyValueId3 = document.getElementById('price_currency_value_id3'+i);
				
				var currencySymbolId0 = document.getElementById('price_currency_symbol_id0'+i);
				var currencySymbolId1 = document.getElementById('price_currency_symbol_id1'+i);
				var currencySymbolId2 = document.getElementById('price_currency_symbol_id2'+i);
//				var currencySymbolId3 = document.getElementById('price_currency_symbol_id3'+i);

				switch(to_ccy) {
					case 'USD':
						convertedCurrencyValue0 = (document.getElementById('price_rate_usd_id0'+i).value != "--")?roundprice(document.getElementById('price_rate_usd_id0'+i).value,0):"--";
						convertedCurrencyValue1 = (document.getElementById('price_rate_usd_id1'+i).value != "--")?roundprice(document.getElementById('price_rate_usd_id1'+i).value,0):"--";
						convertedCurrencyValue2 = (document.getElementById('price_rate_usd_id2'+i).value != "--")?roundprice(document.getElementById('price_rate_usd_id2'+i).value,0):"--";
					//	convertedCurrencyValue3 = (document.getElementById('price_rate_usd_id3'+i).value != "--")?roundprice(document.getElementById('price_rate_usd_id3'+i).value,0):"--";
					break;
					case 'GBP':
						convertedCurrencyValue0 = (document.getElementById('price_rate_gbp_id0'+i).value != "--")?roundprice(document.getElementById('price_rate_gbp_id0'+i).value,0):"--";
						convertedCurrencyValue1 = (document.getElementById('price_rate_gbp_id1'+i).value != "--")?roundprice(document.getElementById('price_rate_gbp_id1'+i).value,0):"--";
						convertedCurrencyValue2 = (document.getElementById('price_rate_gbp_id2'+i).value != "--")?roundprice(document.getElementById('price_rate_gbp_id2'+i).value,0):"--";
					//	convertedCurrencyValue3 = (document.getElementById('price_rate_gbp_id3'+i).value != "--")?roundprice(document.getElementById('price_rate_gbp_id3'+i).value,0):"--";
					break;
					case 'EUR':
						convertedCurrencyValue0 = (document.getElementById('price_rate_eur_id0'+i).value != "--")?roundprice(document.getElementById('price_rate_eur_id0'+i).value,0):"--";
						convertedCurrencyValue1 = (document.getElementById('price_rate_eur_id1'+i).value != "--")?roundprice(document.getElementById('price_rate_eur_id1'+i).value,0):"--";
						convertedCurrencyValue2 = (document.getElementById('price_rate_eur_id2'+i).value != "--")?roundprice(document.getElementById('price_rate_eur_id2'+i).value,0):"--";
					//	convertedCurrencyValue3 = (document.getElementById('price_rate_eur_id3'+i).value != "--")?roundprice(document.getElementById('price_rate_eur_id3'+i).value,0):"--";
					break;
				}

				if(convertedCurrencyValue0 != "--") {
					currencySymbolId0.innerHTML = getCurrSymbol(to_ccy);
					currencyValueId0.innerHTML = convertedCurrencyValue0;
				}

				if(convertedCurrencyValue1 != "--") {
					currencySymbolId1.innerHTML = getCurrSymbol(to_ccy);
					currencyValueId1.innerHTML = convertedCurrencyValue1;
				}

				if(convertedCurrencyValue2 != "--") {
					currencySymbolId2.innerHTML = getCurrSymbol(to_ccy);
					currencyValueId2.innerHTML = convertedCurrencyValue2;
				}
				/*
				if(convertedCurrencyValue3 != "--") {
					currencySymbolId3.innerHTML = getCurrSymbol(to_ccy);
					currencyValueId3.innerHTML = convertedCurrencyValue3;
				}
				*/
			}
		}

		//Save their currency preference
		save_preferred_ccy(to_ccy);
		return true;
	}

	function showYear(str) {
		var theYear = document.getElementById('strShowYearId')[document.getElementById('strShowYearId').selectedIndex].innerHTML;
		SetCookie("showOwnrAvaYear", parseInt(theYear));
		var caldiv = "";
		var calli = "";
		for(var i=1; i<=4; i++) {
		    caldiv = "calendarsId"+i;
			calli = "strYearli"+i;
			if(i==str) {
				document.getElementById(caldiv).style.display = "block";
			} else {
				document.getElementById(caldiv).style.display = "none";
			}
		}
	}
</script>
<?php
	$dayname 	= array('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31');
	$monthname 	= array('01'=>'Jan','02'=>'Feb','03'=>'Mar','04'=>'Apr','05'=>'May','06'=>'Jun','07'=>'Jul','08'=>'Aug','09'=>'Sep','10'=>'Oct','11'=>'Nov','12'=>'Dec');
	$yearname 	= array(date('Y')+0,date('Y')+1,date('Y')+2,date('Y')+3);
?>
<!-- TinyMCE -->
<script type="text/javascript" src="<?php echo SITE_URL; ?>tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
	tinyMCE.init({
		mode : "exact",
		elements : "txtUserMessageId",
		theme : "simple",
		plugins : 'advlink,advimage',
        relative_urls : false,
		remove_script_host : false
	});
</script>
<!-- /TinyMCE -->
<script language="javascript" type="text/javascript">
// JavaScript Document
	var req = ajaxFunction();
	var x1 = "";
	var y1 = "";
	var x, y;

// Simulates PHP's date function
Date.prototype.format = function(format) {
	var returnStr = '';
	var replace = Date.replaceChars;
	for (var i = 0; i < format.length; i++) {
		var curChar = format.charAt(i);
		if (i - 1 >= 0 && format.charAt(i - 1) == "\\") { 
			returnStr += curChar;
		}
		else if (replace[curChar]) {
			returnStr += replace[curChar].call(this);
		} else if (curChar != "\\"){
			returnStr += curChar;
		}
	}
	return returnStr;
};
 
Date.replaceChars = {
	shortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
	longMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
	shortDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
	longDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
	
	// Day
	d: function() { return (this.getDate() < 10 ? '0' : '') + this.getDate(); },
	D: function() { return Date.replaceChars.shortDays[this.getDay()]; },
	j: function() { return this.getDate(); },
	l: function() { return Date.replaceChars.longDays[this.getDay()]; },
	N: function() { return this.getDay() + 1; },
	S: function() { return (this.getDate() % 10 == 1 && this.getDate() != 11 ? 'st' : (this.getDate() % 10 == 2 && this.getDate() != 12 ? 'nd' : (this.getDate() % 10 == 3 && this.getDate() != 13 ? 'rd' : 'th'))); },
	w: function() { return this.getDay(); },
	z: function() { var d = new Date(this.getFullYear(),0,1); return Math.ceil((this - d) / 86400000); }, // Fixed now
	// Week
	W: function() { var d = new Date(this.getFullYear(), 0, 1); return Math.ceil((((this - d) / 86400000) + d.getDay() + 1) / 7); }, // Fixed now
	// Month
	F: function() { return Date.replaceChars.longMonths[this.getMonth()]; },
	m: function() { return (this.getMonth() < 9 ? '0' : '') + (this.getMonth() + 1); },
	M: function() { return Date.replaceChars.shortMonths[this.getMonth()]; },
	n: function() { return this.getMonth() + 1; },
	t: function() { var d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 0).getDate() }, // Fixed now, gets #days of date
	// Year
	L: function() { var year = this.getFullYear(); return (year % 400 == 0 || (year % 100 != 0 && year % 4 == 0)); },	// Fixed now
	o: function() { var d  = new Date(this.valueOf());  d.setDate(d.getDate() - ((this.getDay() + 6) % 7) + 3); return d.getFullYear();}, //Fixed now
	Y: function() { return this.getFullYear(); },
	y: function() { return ('' + this.getFullYear()).substr(2); },
	// Time
	a: function() { return this.getHours() < 12 ? 'am' : 'pm'; },
	A: function() { return this.getHours() < 12 ? 'AM' : 'PM'; },
	B: function() { return Math.floor((((this.getUTCHours() + 1) % 24) + this.getUTCMinutes() / 60 + this.getUTCSeconds() / 3600) * 1000 / 24); }, // Fixed now
	g: function() { return this.getHours() % 12 || 12; },
	G: function() { return this.getHours(); },
	h: function() { return ((this.getHours() % 12 || 12) < 10 ? '0' : '') + (this.getHours() % 12 || 12); },
	H: function() { return (this.getHours() < 10 ? '0' : '') + this.getHours(); },
	i: function() { return (this.getMinutes() < 10 ? '0' : '') + this.getMinutes(); },
	s: function() { return (this.getSeconds() < 10 ? '0' : '') + this.getSeconds(); },
	u: function() { var m = this.getMilliseconds(); return (m < 10 ? '00' : (m < 100 ?
'0' : '')) + m; },
	// Timezone
	e: function() { return "Not Yet Supported"; },
	I: function() { return "Not Yet Supported"; },
	O: function() { return (-this.getTimezoneOffset() < 0 ? '-' : '+') + (Math.abs(this.getTimezoneOffset() / 60) < 10 ? '0' : '') + (Math.abs(this.getTimezoneOffset() / 60)) + '00'; },
	P: function() { return (-this.getTimezoneOffset() < 0 ? '-' : '+') + (Math.abs(this.getTimezoneOffset() / 60) < 10 ? '0' : '') + (Math.abs(this.getTimezoneOffset() / 60)) + ':00'; }, // Fixed now
	T: function() { var m = this.getMonth(); this.setMonth(0); var result = this.toTimeString().replace(/^.+ \(?([^\)]+)\)?$/, '$1'); this.setMonth(m); return result;},
	Z: function() { return -this.getTimezoneOffset() * 60; },
	// Full Date/Time
	c: function() { return this.format("Y-m-d\\TH:i:sP"); }, // Fixed now
	r: function() { return this.toString(); },
	U: function() { return this.getTime() / 1000; }
};


	function find_cal(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;				
				x1 = x+160;
				y1 = y-153;
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function find_cal2(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal1.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				x1 = x-120;
				y1 = y-153;
				object = req.responseText;				
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function find_cal3(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;				
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function find_cal4(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal3.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;				
				x1 = x+160;
				y1 = y-153;
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function find_cal5(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal3.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;				
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}


	function insert_date1(dt,sid){
		var dateString = String(dt);
		var dateBody = dateString.split("/");
		var arrival = String(dateBody[2])+"-"+String(dateBody[0])+"-"+String(dateBody[1]);
		var duration = document.getElementById("txtDurationId").value;
		var departure_date = new Date();
		departure_date.setFullYear(parseInt(dateBody[2], 10), parseInt((dateBody[0]-1), 10), (parseInt(dateBody[1], 10)+parseInt(duration, 10)));
		var departure = departure_date.format('Y-m-d');
		document.getElementById("txtArriavalDate").value = arrival;
		document.getElementById("txtDepartureDate").value = departure;
		changeTripDuration(<?php echo $property_id;?>, arrival, departure, duration);
		document.getElementById("CalendarDiv").style.display = "none";
	}

	function close_calendar(){		
		document.getElementById("CalendarDiv").style.display = "none";
	}
 
	/*
	* For booing engine: Start here
	*/
	function changeTripDuration(pid, frm, dep, stay) {
		var url = "<?php echo SITE_URL; ?>property-booking-ajax.php?pid="+pid+"&frm="+frm+"&dep="+dep+"&stay="+stay+"&currency_code=<?php echo $users_currency_code;?>";
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;
				document.getElementById("bookNowId").innerHTML = object;
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function submitTripDuration(arival, departure) {
		document.getElementById("txtArriavalDate").value = arival;
		document.getElementById("txtDepartureDate").value = departure;
		document.getElementById("frmPropertyBooking").submit();
	}
	
	function enabledateChoose() {
		if(document.getElementById("txtDurationId").value == "") {
			document.getElementById("txtDateChooserOn").style.display = "none";
			document.getElementById("txtDateChooserOff").style.display = "block";
		} else {
			document.getElementById("txtDateChooserOn").style.display = "block";
			document.getElementById("txtDateChooserOff").style.display = "none";
		}
	}
	/*
	* For booing engine: End here
	*/
</script>
<table width="100%"  cellpadding="0" cellspacing="0" border="0" class="font12">
	<?php
	if(is_array($propertyPricesArr) && count($propertyPricesArr) > 0){
	?>
    <tr>
        <td align="left" valign="top" class="pad-top15">
            <table border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="pad-rgt20"><strong><?php echo tranText('quoted_in'); ?>:</strong> <?php echo $property_currency_symbol." ".ucwords($propertyObj->fun_findPropertyCurrencyName($property_id));?></td>
                    <td class="pad-rgt7"><strong><?php echo tranText('see_approximate_prices_in'); ?></strong></td>
                    <td align="right">
                        <select name="txtCurrencyType" id="txtCurrencyType" class="PropertyListingCurrency" style="width:175px;" onchange="convertCurrency(this.value);">
                            <?php $propertyObj->fun_getCurrenciesOptionsListWithCodeSymbl($currency_code); ?>
                        </select>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td align="left" valign="top" class="pad-top20">
        <?php
				$minStayArr = array();
                echo "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n";
                echo "<tr>\n";
                echo "<td class=\"PricesBlankHead\" colspan=\"7\"></td>\n";
                echo "</tr>\n";
                echo "<tr>\n";
                echo "<td class=\"PricesHeadV\">Date from</td>\n";
                echo "<td class=\"PricesHeadV\">Date to</td>\n";
                echo "<td align=\"center\" class=\"PricesHeadV\">Min stay</td>\n";
                echo "<td align=\"center\" class=\"PricesHeadV\">Price / night </td>\n";
                echo "<td align=\"center\" class=\"PricesHeadV\">Price / week </td>\n";
                echo "<td align=\"center\" class=\"PricesHeadV\">Price / month </td>\n";
                echo "<td align=\"center\" class=\"PricesHeadV\">Note</td>\n";
                echo "</tr>\n";
                $showSpecialOfferIcon = false;
                for($i=0; $i<count($propertyPricesArr); $i++){
                    $property_price_id		= $propertyPricesArr[$i]['id'];
                    $dateFrom 				= date('M j, Y', $propertyPricesArr[$i]['date_from']);
                    $dateTo 				= date('M j, Y', $propertyPricesArr[$i]['date_to']);
                    $minStay 				= $propertyPricesArr[$i]['min_stay'];
                    array_push($minStayArr, $minStay);
                    $stayType 				= $propertyPricesArr[$i]['min_stay_type'];
                    
                    if((int)$minStay > 1) {
                        $strMinStay			= $propertyPricesArr[$i]['min_stay'] ." ".(($stayType == "w") ? "Weeks" : "Nights");
                    } else if((int)$minStay == 1){
                        $strMinStay			= $propertyPricesArr[$i]['min_stay'] ." ".(($stayType == "w") ? "Week" : "Night");
                    } else {
                        $strMinStay			= "--";
                    }
                    $specialOffer 			= $propertyPricesArr[$i]['special_offer'];
                    if($specialOffer > 0) { 
                        $showSpecialOfferIcon = true;
                        $tdStyle = "pricesSpecialV";
                    } else {
                        $tdStyle = "PricesBlankV";
                    }
                    $priceName 				= $propertyPricesArr[$i]['price_name'];

                    echo "<tr><td>";
                    if($propertyPricesArr[$i]['per_month_price'] > 0) {
                        $perMonthPrice 			= $propertyObj->fun_getConvertedCurrency($property_currency_id, $users_currency_id, $propertyPricesArr[$i]['per_month_price']);
                        echo "<input name=\"price_rate_usd_0".$i."\"  id=\"price_rate_usd_id0".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_month_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['USD'])."\" />\n";
                        echo "<input name=\"price_rate_gbp_0".$i."\"  id=\"price_rate_gbp_id0".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_month_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['GBP'])."\" />\n";
                        echo "<input name=\"price_rate_eur_0".$i."\"  id=\"price_rate_eur_id0".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_month_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['EUR'])."\" />\n";
                    } else {
                        $perMonthPrice 			= "--";
                        echo "<input name=\"price_rate_usd_0".$i."\"  id=\"price_rate_usd_id0".$i."\" type=\"hidden\" value=\"--\" />\n";
                        echo "<input name=\"price_rate_gbp_0".$i."\"  id=\"price_rate_gbp_id0".$i."\" type=\"hidden\" value=\"--\" />\n";
                        echo "<input name=\"price_rate_eur_0".$i."\"  id=\"price_rate_eur_id0".$i."\" type=\"hidden\" value=\"--\" />\n";
                    }

                    if($propertyPricesArr[$i]['per_week_price'] > 0) {
                        $perWeekPrice 			= $propertyObj->fun_getConvertedCurrency($property_currency_id, $users_currency_id, $propertyPricesArr[$i]['per_week_price']);
                        echo "<input name=\"price_rate_usd_1".$i."\"  id=\"price_rate_usd_id1".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_week_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['USD'])."\" />\n";
                        echo "<input name=\"price_rate_gbp_1".$i."\"  id=\"price_rate_gbp_id1".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_week_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['GBP'])."\" />\n";
                        echo "<input name=\"price_rate_eur_1".$i."\"  id=\"price_rate_eur_id1".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_week_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['EUR'])."\" />\n";
                    } else {
                        $perWeekPrice 			= "--";
                        echo "<input name=\"price_rate_usd_1".$i."\"  id=\"price_rate_usd_id1".$i."\" type=\"hidden\" value=\"--\" />\n";
                        echo "<input name=\"price_rate_gbp_1".$i."\"  id=\"price_rate_gbp_id1".$i."\" type=\"hidden\" value=\"--\" />\n";
                        echo "<input name=\"price_rate_eur_1".$i."\"  id=\"price_rate_eur_id1".$i."\" type=\"hidden\" value=\"--\" />\n";
                    }

                    if($propertyPricesArr[$i]['per_night_midweek_price'] > 0) {
                        $perNightMidweekPrice	= $propertyObj->fun_getConvertedCurrency($property_currency_id, $users_currency_id, $propertyPricesArr[$i]['per_night_midweek_price']);
                        echo "<input name=\"price_rate_usd_2".$i."\"  id=\"price_rate_usd_id2".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_night_midweek_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['USD'])."\" />\n";
                        echo "<input name=\"price_rate_gbp_2".$i."\"  id=\"price_rate_gbp_id2".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_night_midweek_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['GBP'])."\" />\n";
                        echo "<input name=\"price_rate_eur_2".$i."\"  id=\"price_rate_eur_id2".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_night_midweek_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['EUR'])."\" />\n";
                    } else {
                        $perNightMidweekPrice	= "--";
                        echo "<input name=\"price_rate_usd_2".$i."\"  id=\"price_rate_usd_id2".$i."\" type=\"hidden\" value=\"--\" />\n";
                        echo "<input name=\"price_rate_gbp_2".$i."\"  id=\"price_rate_gbp_id2".$i."\" type=\"hidden\" value=\"--\" />\n";
                        echo "<input name=\"price_rate_eur_2".$i."\"  id=\"price_rate_eur_id2".$i."\" type=\"hidden\" value=\"--\" />\n";
                    }

                    echo "</td></tr>";
                    echo "<tr id=\"price_row_id".$property_price_id."\" >\n";
                    echo "<td align=\"left\" class=\"".$tdStyle."\">".$dateFrom."</td>\n";
                    echo "<td align=\"left\" class=\"".$tdStyle."\">".$dateTo."</td>\n";
                    echo "<td align=\"center\" class=\"".$tdStyle."\">".$strMinStay."</td>\n";
                    echo "<td align=\"center\" class=\"".$tdStyle."\" id=\"price_cell_id2".$i."\">\n";
                    if(is_numeric($perNightMidweekPrice)) {
                        echo "<span id=\"price_currency_symbol_id2".$i."\">".$users_currency_symbol."</span><span id=\"price_currency_value_id2".$i."\">".number_format($perNightMidweekPrice)."</span>\n";
                    } else {
                        echo "<span id=\"price_currency_symbol_id2".$i."\">&nbsp;</span><span id=\"price_currency_value_id2".$i."\">".$perNightMidweekPrice."</span>\n";
                    }
                    echo "</td>\n";
                    echo "<td align=\"center\" class=\"".$tdStyle."\" id=\"price_cell_id1".$i."\">\n";
                    if(is_numeric($perWeekPrice)) {
                        echo "<span id=\"price_currency_symbol_id1".$i."\">".$users_currency_symbol."</span><span id=\"price_currency_value_id1".$i."\">".number_format($perWeekPrice)."</span>\n";
                    } else {
                        echo "<span id=\"price_currency_symbol_id1".$i."\">&nbsp;</span><span id=\"price_currency_value_id1".$i."\">".$perWeekPrice."</span>\n";
                    }
                    echo "</td>\n";
                    echo "<td align=\"center\" class=\"".$tdStyle."\" id=\"price_cell_id0".$i."\">\n";
                    if(is_numeric($perMonthPrice)) {
                        echo "<span id=\"price_currency_symbol_id0".$i."\">".$users_currency_symbol."</span><span id=\"price_currency_value_id0".$i."\">".number_format($perMonthPrice)."</span>\n";
                    } else {
                        echo "<span id=\"price_currency_symbol_id0".$i."\">&nbsp;</span><span id=\"price_currency_value_id0".$i."\">".$perMonthPrice."</span>\n";
                    }
                    echo "</td>\n";
                    echo "<td align=\"left\" class=\"".$tdStyle."\">".$priceName."</td>\n";
                    echo "</tr>\n";
                }
                echo "</table>\n";
            ?>
        </td>
    </tr>
    <tr>
        <td class="pad-top10 pad-btm10" valign="top" align="left">
        <?php
            if($showSpecialOfferIcon == true) {
                echo "<span class=\"special-offer\"> = Special offer</span>";
            } else {
                echo "&nbsp;";
            }
        ?>
        </td>
    </tr>
    <tr>
        <td class="pad-top10 pad-btm10" valign="top" align="left">
            <?php 
            $price_notes = $propertyObj->fun_getPropertyPriceNotes($property_id); 
            if($price_notes != "") {
            ?>
                <div class="pad-btm5"><span class="font12"><?php echo tranText('notes_on_rates'); ?>...</span></div>
                <p><?php echo $price_notes; ?></p>
            <?php
            }
            ?>
        </td>
    </tr>
	<?php
    } else {
		echo '<tr>';
		echo '<td class="pad-top10 pad-btm10" valign="top" align="left">';
		echo '<strong>For rental cost contact owner ...</strong>';
		echo '</td>';
		echo '</tr>';
	}	
    ?>
</table>
