<?php
//For price
//shifted to upper page
//	$propertyPricesArr 		= $propertyObj->fun_getPropertyPricesArr($property_id);
//	$propertyCurrencyId		= $propertyObj->fun_findPropertyCurrencyCode($property_id);
//	$propertyCurrencySymbol	= $propertyObj->fun_findPropertyCurrencySymbol($property_id, '');
//	$currencyRateArr		= $propertyObj->fun_findPropertyCurrencyRate();


	$propertyAvailInfo 		= $propertyObj->fun_getPropertyAvailabilityArr($property_id);

	//print_r($currencyRateArr);

	//For availability
	require_once(SITE_CLASSES_PATH."class.Calender.php");
	$calendarObj = new Calendar();
    $yearname 	= array(date('Y')+0,date('Y')+1,date('Y')+2,date('Y')+3);
	list($year1, $year2, $year3, $year4) = $yearname;
?>

<script language="javascript">
	var req = ajaxFunction();
	//************ NOTE: DO NOT EDIT THIS FILE MANUALLY *************
	var gh_rates = new Object;
	gh_rates["USD"]=<?php echo $currencyRateArr['USD']; ?>;
	gh_rates["GBP"]=<?php echo $currencyRateArr['GBP']; ?>;
	gh_rates["EUR"]=<?php echo $currencyRateArr['EUR']; ?>;
	//************ NOTE: DO NOT EDIT THIS FILE MANUALLY *************

	function getCurrSymbol(lscurr) {
		var lsOut;
		//alert('getCurrSymbol()');
		switch(lscurr) {
			case "USD": lsOut = "$"; break;
			case "EUR": lsOut = "&euro;"; break;
			case "GBP": lsOut = "&pound;"; break;
		}
		return lsOut;
	}

	function roundprice(rprice, rbpence) { 
		//rprice [the full price to be rounded]
		//rbpence flag to specify to round to pence(3.99) or to pound(3)[  1=pence 0=pounds ]
		//rprice=222.5; rbpence=1;
		
		//alert('roundpence() rprice='+rprice + ' rbpence='+rbpence);
		var mystr = rprice.toString();
		var mypos=mystr.indexOf(".");
		//alert('roundpence() mypos='+mypos);
		if (mypos==-1)  {
			retval=mystr;
			//Put comma in to represent thousand separator - what a pain!!
			//alert('leaving here');
			
			
			if (rbpence==1)   {
				//No decimal place, so add the .00
				retval=mystr+'.00'
			}
		} else  {	
		
			if (rbpence==1)  {
				//Add a ZERO if only one number after the decimal place
				//Get the bit before the decimal place
				var after = mystr.slice(mypos+1);
				//alert('a) after='+after);
				if (after.length==1)  {  //dp+1digit==2
					after=after+'0';
					//alert('b) after='+after);
				} else  {
					//Get 3 digits (if they exist) so we can round properly
					//alert('after=' + after);
					
					if (after.length > 2 )  {
						after=after.slice(0,2) + '.' + after.slice(2,3);
						//Rounds to 2 dp
						after=Math.round(after);
					}
					//alert('after slice=' + after);
				}
				retval=mystr.slice(0,mypos) + '.' + after;
			} else  {
				//Just return the bit before the decimal place
				//retval=mystr.slice(0,mypos);
				retval=Math.round(mystr)
			}
			
			
		}
		//alert('roundpence() retval='+retval);
		return addCommas(retval);
	}

	function addCommas(nStr)
	{
		nStr += '';
		x = nStr.split('.');
		x1 = x[0];
		x2 = x.length > 1 ? '.' + x[1] : '';
		var rgx = /(\d+)(\d{3})/;
		while (rgx.test(x1)) {
			x1 = x1.replace(rgx, '$1' + ',' + '$2');
		}
		return x1 + x2;
	}


	//Save their currency preference
	function save_preferred_ccy(curcode) {
		req.open('get', '<?php echo SITE_URL;?>setUserCurrency.php?curcode=' + curcode); 
		req.send(null); 
	}


	function convertCurrency(to_ccy) { 

		var cntPriceArr	= <?php echo count($propertyPricesArr); ?>;
		
		if(parseInt(cntPriceArr) > 0) {
			for (var i = 0; i < cntPriceArr; i++)  {
				//Get Amounts
				var currencyValueId1 = document.getElementById('price_currency_value_id1'+i);
//				var currencyValueId2 = document.getElementById('price_currency_value_id2'+i);
//				var currencyValueId3 = document.getElementById('price_currency_value_id3'+i);
				
				var currencySymbolId1 = document.getElementById('price_currency_symbol_id1'+i);
//				var currencySymbolId2 = document.getElementById('price_currency_symbol_id2'+i);
//				var currencySymbolId3 = document.getElementById('price_currency_symbol_id3'+i);

				switch(to_ccy) {
					case 'USD':
						convertedCurrencyValue1 = (document.getElementById('price_rate_usd_id1'+i).value != "--")?roundprice(document.getElementById('price_rate_usd_id1'+i).value,0):"--";
					//	convertedCurrencyValue2 = (document.getElementById('price_rate_usd_id2'+i).value != "--")?roundprice(document.getElementById('price_rate_usd_id2'+i).value,0):"--";
					//	convertedCurrencyValue3 = (document.getElementById('price_rate_usd_id3'+i).value != "--")?roundprice(document.getElementById('price_rate_usd_id3'+i).value,0):"--";
					break;
					case 'GBP':
						convertedCurrencyValue1 = (document.getElementById('price_rate_gbp_id1'+i).value != "--")?roundprice(document.getElementById('price_rate_gbp_id1'+i).value,0):"--";
					//	convertedCurrencyValue2 = (document.getElementById('price_rate_gbp_id2'+i).value != "--")?roundprice(document.getElementById('price_rate_gbp_id2'+i).value,0):"--";
					//	convertedCurrencyValue3 = (document.getElementById('price_rate_gbp_id3'+i).value != "--")?roundprice(document.getElementById('price_rate_gbp_id3'+i).value,0):"--";
					break;
					case 'EUR':
						convertedCurrencyValue1 = (document.getElementById('price_rate_eur_id1'+i).value != "--")?roundprice(document.getElementById('price_rate_eur_id1'+i).value,0):"--";
					//	convertedCurrencyValue2 = (document.getElementById('price_rate_eur_id2'+i).value != "--")?roundprice(document.getElementById('price_rate_eur_id2'+i).value,0):"--";
					//	convertedCurrencyValue3 = (document.getElementById('price_rate_eur_id3'+i).value != "--")?roundprice(document.getElementById('price_rate_eur_id3'+i).value,0):"--";
					break;
				}

				if(convertedCurrencyValue1 != "--") {
					currencySymbolId1.innerHTML = getCurrSymbol(to_ccy);
					currencyValueId1.innerHTML = convertedCurrencyValue1;
				}

/*
				if(convertedCurrencyValue2 != "--") {
					currencySymbolId2.innerHTML = getCurrSymbol(to_ccy);
					currencyValueId2.innerHTML = convertedCurrencyValue2;
				}
				if(convertedCurrencyValue3 != "--") {
					currencySymbolId3.innerHTML = getCurrSymbol(to_ccy);
					currencyValueId3.innerHTML = convertedCurrencyValue3;
				}
*/
			}
		}

		//Save their currency preference
		save_preferred_ccy(to_ccy);
		return true;
	}

	function showYear(str) {
		var theYear = document.getElementById('strShowYearId')[document.getElementById('strShowYearId').selectedIndex].innerHTML;
		SetCookie("showOwnrAvaYear", parseInt(theYear));
		var caldiv = "";
		var calli = "";
		for(var i=1; i<=4; i++) {
		    caldiv = "calendarsId"+i;
			calli = "strYearli"+i;
			if(i==str) {
				document.getElementById(caldiv).style.display = "block";
			} else {
				document.getElementById(caldiv).style.display = "none";
			}
		}
	}
</script>
<?php
	$dayname 	= array('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31');
	$monthname 	= array('01'=>'Jan','02'=>'Feb','03'=>'Mar','04'=>'Apr','05'=>'May','06'=>'Jun','07'=>'Jul','08'=>'Aug','09'=>'Sep','10'=>'Oct','11'=>'Nov','12'=>'Dec');
	$yearname 	= array(date('Y')+0,date('Y')+1,date('Y')+2,date('Y')+3);
?>
<!-- TinyMCE -->
<script type="text/javascript" src="<?php echo SITE_URL; ?>tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
	tinyMCE.init({
		mode : "exact",
		elements : "txtUserMessageId",
		theme : "simple"
	});
</script>
<!-- /TinyMCE -->
<script language="javascript" type="text/javascript">
// JavaScript Document
	var req = ajaxFunction();
	var x1 = "";
	var y1 = "";
	var x, y;

// Simulates PHP's date function
Date.prototype.format = function(format) {
	var returnStr = '';
	var replace = Date.replaceChars;
	for (var i = 0; i < format.length; i++) {
		var curChar = format.charAt(i);
		if (i - 1 >= 0 && format.charAt(i - 1) == "\\") { 
			returnStr += curChar;
		}
		else if (replace[curChar]) {
			returnStr += replace[curChar].call(this);
		} else if (curChar != "\\"){
			returnStr += curChar;
		}
	}
	return returnStr;
};
 
Date.replaceChars = {
	shortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
	longMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
	shortDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
	longDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
	
	// Day
	d: function() { return (this.getDate() < 10 ? '0' : '') + this.getDate(); },
	D: function() { return Date.replaceChars.shortDays[this.getDay()]; },
	j: function() { return this.getDate(); },
	l: function() { return Date.replaceChars.longDays[this.getDay()]; },
	N: function() { return this.getDay() + 1; },
	S: function() { return (this.getDate() % 10 == 1 && this.getDate() != 11 ? 'st' : (this.getDate() % 10 == 2 && this.getDate() != 12 ? 'nd' : (this.getDate() % 10 == 3 && this.getDate() != 13 ? 'rd' : 'th'))); },
	w: function() { return this.getDay(); },
	z: function() { var d = new Date(this.getFullYear(),0,1); return Math.ceil((this - d) / 86400000); }, // Fixed now
	// Week
	W: function() { var d = new Date(this.getFullYear(), 0, 1); return Math.ceil((((this - d) / 86400000) + d.getDay() + 1) / 7); }, // Fixed now
	// Month
	F: function() { return Date.replaceChars.longMonths[this.getMonth()]; },
	m: function() { return (this.getMonth() < 9 ? '0' : '') + (this.getMonth() + 1); },
	M: function() { return Date.replaceChars.shortMonths[this.getMonth()]; },
	n: function() { return this.getMonth() + 1; },
	t: function() { var d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 0).getDate() }, // Fixed now, gets #days of date
	// Year
	L: function() { var year = this.getFullYear(); return (year % 400 == 0 || (year % 100 != 0 && year % 4 == 0)); },	// Fixed now
	o: function() { var d  = new Date(this.valueOf());  d.setDate(d.getDate() - ((this.getDay() + 6) % 7) + 3); return d.getFullYear();}, //Fixed now
	Y: function() { return this.getFullYear(); },
	y: function() { return ('' + this.getFullYear()).substr(2); },
	// Time
	a: function() { return this.getHours() < 12 ? 'am' : 'pm'; },
	A: function() { return this.getHours() < 12 ? 'AM' : 'PM'; },
	B: function() { return Math.floor((((this.getUTCHours() + 1) % 24) + this.getUTCMinutes() / 60 + this.getUTCSeconds() / 3600) * 1000 / 24); }, // Fixed now
	g: function() { return this.getHours() % 12 || 12; },
	G: function() { return this.getHours(); },
	h: function() { return ((this.getHours() % 12 || 12) < 10 ? '0' : '') + (this.getHours() % 12 || 12); },
	H: function() { return (this.getHours() < 10 ? '0' : '') + this.getHours(); },
	i: function() { return (this.getMinutes() < 10 ? '0' : '') + this.getMinutes(); },
	s: function() { return (this.getSeconds() < 10 ? '0' : '') + this.getSeconds(); },
	u: function() { var m = this.getMilliseconds(); return (m < 10 ? '00' : (m < 100 ?
'0' : '')) + m; },
	// Timezone
	e: function() { return "Not Yet Supported"; },
	I: function() { return "Not Yet Supported"; },
	O: function() { return (-this.getTimezoneOffset() < 0 ? '-' : '+') + (Math.abs(this.getTimezoneOffset() / 60) < 10 ? '0' : '') + (Math.abs(this.getTimezoneOffset() / 60)) + '00'; },
	P: function() { return (-this.getTimezoneOffset() < 0 ? '-' : '+') + (Math.abs(this.getTimezoneOffset() / 60) < 10 ? '0' : '') + (Math.abs(this.getTimezoneOffset() / 60)) + ':00'; }, // Fixed now
	T: function() { var m = this.getMonth(); this.setMonth(0); var result = this.toTimeString().replace(/^.+ \(?([^\)]+)\)?$/, '$1'); this.setMonth(m); return result;},
	Z: function() { return -this.getTimezoneOffset() * 60; },
	// Full Date/Time
	c: function() { return this.format("Y-m-d\\TH:i:sP"); }, // Fixed now
	r: function() { return this.toString(); },
	U: function() { return this.getTime() / 1000; }
};


	function find_cal(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;				
				x1 = x+160;
				y1 = y-153;
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function find_cal2(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal1.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				x1 = x-120;
				y1 = y-153;
				object = req.responseText;				
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function find_cal3(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;				
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function find_cal4(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal3.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;				
				x1 = x+160;
				y1 = y-153;
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function find_cal5(a,ct){
		var url="<?php echo SITE_URL; ?>get_cal3.php";
		url=url+"?timestamp="+a+"&ct="+ct;
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;				
				var googlewin=dhtmlwindow.open("CalendarDiv", "inline", object, " ", "width=235px,height=285px,resize=0,scrolling=0,center=1,xAxis="+x1+",yAxis="+y1+"", "recal");
				googlewin.onclose=function(){ //Run custom code when window is being closed (return false to cancel action):
					return true
				}
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}


	function insert_date1(dt,sid){
		var dateString = String(dt);
		var dateBody = dateString.split("/");
		var arrival = String(dateBody[2])+"-"+String(dateBody[0])+"-"+String(dateBody[1]);
		var duration = document.getElementById("txtDurationId").value;
		var departure_date = new Date();
		departure_date.setFullYear(parseInt(dateBody[2], 10), parseInt((dateBody[0]-1), 10), (parseInt(dateBody[1], 10)+parseInt(duration, 10)));
		var departure = departure_date.format('Y-m-d');
		document.getElementById("txtArriavalDate").value = arrival;
		document.getElementById("txtDepartureDate").value = departure;
		changeTripDuration(<?php echo $property_id;?>, arrival, departure, duration);
		document.getElementById("CalendarDiv").style.display = "none";
	}

	function close_calendar(){		
		document.getElementById("CalendarDiv").style.display = "none";
	}
 
	/*
	* For booing engine: Start here
	*/
	function changeTripDuration(pid, frm, dep, stay) {
		var url = "<?php echo SITE_URL; ?>property-booking-ajax.php?pid="+pid+"&frm="+frm+"&dep="+dep+"&stay="+stay+"&currency_code=<?php echo $users_currency_code;?>";
		req.onreadystatechange=function(){
			if (req.readyState==4){
				var object;
				object = req.responseText;
				document.getElementById("bookNowId").innerHTML = object;
			}
		}
		req.open("GET",url,true);
		req.send(null);
	}

	function submitTripDuration(arival, departure) {
		document.getElementById("txtArriavalDate").value = arival;
		document.getElementById("txtDepartureDate").value = departure;
		document.getElementById("frmPropertyBooking").submit();
	}
	
	function enabledateChoose() {
		if(document.getElementById("txtDurationId").value == "") {
			document.getElementById("txtDateChooserOn").style.display = "none";
			document.getElementById("txtDateChooserOff").style.display = "block";
		} else {
			document.getElementById("txtDateChooserOn").style.display = "block";
			document.getElementById("txtDateChooserOff").style.display = "none";
		}
	}
	/*
	* For booing engine: End here
	*/
</script>
<table border="0" align="left" cellpadding="0" cellspacing="0"  width="100%">
    <tr>
        <td valign="top">
            <div id="tab-wrap changed_tab-wrap">
                <div id="tab_menu" >
                    <ul style="padding-left:100px;">
                        <li><a href="javascript:void(0);" onclick="return showSection(1);" title="Description" class="smallfont" ><?php echo tranText('overview'); ?></a></li>
                        <li><a href="javascript:void(0);" onclick="return showSection(3);" title="Amenities" class="smallfont"><?php echo tranText('accommodation_amenities'); ?></a></li>
                        <li id="current"><a href="javascript:void(0);" title="Availability - Prices" class="smallfont"><?php echo tranText('rates_book'); ?></a></li>
                        <li><a href="javascript:void(0);" onclick="return showSection(4);" title="Location" class="smallfont"><?php echo tranText('location'); ?></a></li>
                        <?php /*?> 
                       <li><a href="javascript:void(0);" onclick="return showSection(5);" title="Reviews" class="smallfont">Read <?php if(isset($total_reviews) && $total_reviews > 1){echo "/add reviews  ";} else {echo "/add reviews  ";} ?>(<?php echo $total_reviews; ?>)</a></li>
					   <?php */?> 
                        <li><a href="javascript:void(0);" onclick="return showSection(5);" title="Reviews" class="smallfont"><?php echo tranText('read_add_reviews'); ?></a></li>
                       <li><a href="javascript:void(0);" onclick="return showSection(6);" title="Contact Owner" class="smallfont"><?php echo tranText('contact'); ?></a></li>
                    </ul>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td valign="top" class="pad-top20">
            <!-- property inner tabs : start here -->
            <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                    <td align="left">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="580px" valign="top" align="left">
                                    <table width="100%"  cellpadding="0" cellspacing="0" border="0" class="font12">
                                        <tr><td valign="top"><p class="gray14"><?php echo tranText('property_rates'); ?>...</p></td></tr>
                                        <tr>
                                            <td align="left" valign="top" class="pad-top15">
                                                <table border="0" cellspacing="0" cellpadding="0">
                                                    <tr>
                                                        <td class="pad-rgt20"><strong><?php echo tranText('quoted_in'); ?>:</strong> <?php echo $property_currency_symbol." ".ucwords($propertyObj->fun_findPropertyCurrencyName($property_id));?></td>
                                                        <td class="pad-rgt7"><strong><?php echo tranText('see_approximate_prices_in'); ?></strong></td>
                                                        <td align="right">
                                                            <select name="txtCurrencyType" id="txtCurrencyType" class="PropertyListingCurrency" style="width:175px;" onchange="convertCurrency(this.value);">
                                                                <?php $propertyObj->fun_getCurrenciesOptionsListWithCodeSymbl($currency_code); ?>
                                                            </select>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="top" class="pad-top20 pad-rgt20">
                                            <?php
												$minStayArr = array();
                                                if(count($propertyPricesArr) > 0){
                                                    echo "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n";
                                                    echo "<tr>\n";
                                                    echo "<td class=\"PricesBlankHead\" colspan=\"5\"></td>\n";
                                                    echo "</tr>\n";
                                                    echo "<tr>\n";
                                                    echo "<td class=\"PricesHeadV\">Date from</td>\n";
                                                    echo "<td class=\"PricesHeadV\">Date to</td>\n";
                                                    echo "<td align=\"center\" class=\"PricesHeadV\">Min stay</td>\n";
                                                    echo "<td align=\"center\" class=\"PricesHeadV\">Price / week </td>\n";
                                                    echo "<td align=\"center\" class=\"PricesHeadV\">Note</td>\n";
                                                    echo "</tr>\n";
													$showSpecialOfferIcon = false;
                                                    for($i=0; $i<count($propertyPricesArr); $i++){
                                                        $property_price_id		= $propertyPricesArr[$i]['id'];
                                                        $dateFrom 				= date('F j, Y', strtotime($propertyPricesArr[$i]['date_from']));
                                                        $dateTo 				= date('F j, Y', strtotime($propertyPricesArr[$i]['date_to']));
                                                        $stayType 				= $propertyPricesArr[$i]['min_stay_type'];
                                                        $minStay 				= ($stayType == "w")?($propertyPricesArr[$i]['min_stay']*7):$propertyPricesArr[$i]['min_stay'];
														array_push($minStayArr, $minStay);
                                                        if((int)$minStay > 1) {
                                                            $strMinStay			= $propertyPricesArr[$i]['min_stay'] ." ".(($stayType == "w") ? "Weeks" : "Nights");
                                                        } else if((int)$minStay == 1){
                                                            $strMinStay			= $propertyPricesArr[$i]['min_stay'] ." ".(($stayType == "w") ? "Week" : "Night");
                                                        } else {
                                                            $strMinStay			= "--";
														}
                                                        $specialOffer 			= $propertyPricesArr[$i]['special_offer'];
                                                        if($specialOffer > 0) { 
															$showSpecialOfferIcon = true;
															$tdStyle = "pricesSpecialV";
														} else {
															$tdStyle = "PricesBlankV";
														}
                                                        $priceName 				= $propertyPricesArr[$i]['price_name'];

														echo "<tr><td>";
														if($propertyPricesArr[$i]['per_week_price'] > 0) {
															$perWeekPrice 			= $propertyObj->fun_getConvertedCurrency($property_currency_id, $users_currency_id, $propertyPricesArr[$i]['per_week_price']);
															echo "<input name=\"price_rate_usd_1".$i."\"  id=\"price_rate_usd_id1".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_week_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['USD'])."\" />\n";
															echo "<input name=\"price_rate_gbp_1".$i."\"  id=\"price_rate_gbp_id1".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_week_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['GBP'])."\" />\n";
															echo "<input name=\"price_rate_eur_1".$i."\"  id=\"price_rate_eur_id1".$i."\" type=\"hidden\" value=\"".(($propertyPricesArr[$i]['per_week_price']/$currencyRateArr[$property_currency_code])*$currencyRateArr['EUR'])."\" />\n";
														} else {
															$perWeekPrice 			= "--";
															echo "<input name=\"price_rate_usd_1".$i."\"  id=\"price_rate_usd_id1".$i."\" type=\"hidden\" value=\"--\" />\n";
															echo "<input name=\"price_rate_gbp_1".$i."\"  id=\"price_rate_gbp_id1".$i."\" type=\"hidden\" value=\"--\" />\n";
															echo "<input name=\"price_rate_eur_1".$i."\"  id=\"price_rate_eur_id1".$i."\" type=\"hidden\" value=\"--\" />\n";
														}
								
														echo "</td></tr>";
														echo "<tr id=\"price_row_id".$property_price_id."\" >\n";
														echo "<td align=\"left\" class=\"".$tdStyle."\">".$dateFrom."</td>\n";
														echo "<td align=\"left\" class=\"".$tdStyle."\">".$dateTo."</td>\n";
														echo "<td align=\"center\" class=\"".$tdStyle."\">".$strMinStay."</td>\n";
														echo "<td align=\"center\" class=\"".$tdStyle."\" id=\"price_cell_id1".$i."\">\n";
														if(is_numeric($perWeekPrice)) {
															echo "<span id=\"price_currency_symbol_id1".$i."\">".$users_currency_symbol."</span><span id=\"price_currency_value_id1".$i."\">".number_format($perWeekPrice)."</span>\n";
														} else {
															echo "<span id=\"price_currency_symbol_id1".$i."\">&nbsp;</span><span id=\"price_currency_value_id1".$i."\">".$perWeekPrice."</span>\n";
														}
														
														echo "</td>\n";
														echo "<td align=\"left\" class=\"".$tdStyle."\">".$priceName."</td>\n";
														echo "</tr>\n";
                                                    }
                                                    echo "</table>\n";
                                                }
												?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="pad-top10 pad-btm10" valign="top" align="left">
                                            <?php
												if($showSpecialOfferIcon == true) {
													echo "<span class=\"special-offer\"> = Special offer</span>";
												} else {
													echo "&nbsp;";
												}
											?>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td valign="top" align="left" class="pad-lft20 pad-btm15 font12">
                                <?php 
                                $price_notes = $propertyObj->fun_getPropertyPriceNotes($property_id); 
                                if($price_notes != "") {
                                ?>
                                    <div class="pad-btm5"><span class="font12"><?php echo tranText('notes_on_rates'); ?>...</span></div>
                                    <p><?php echo $price_notes; ?></p>
                                <?php
                                }
                                ?>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr><td align="left" style="border-top:1px dashed #cacaca;">&nbsp;</td></tr>
                <tr>
                    <td align="left" valign="top">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td valign="top" width="550px">
                                    <div class="gray14 pad-lft5 pad-btm20"><?php echo tranText('availability_calender'); ?>...</div>
                                    <div class="calendars">
                                        <div class="FloatLft">
                                            <p class="key"><?php echo tranText('view'); ?></p>
                                            <span>
                                            <select name="strShowYear" id="strShowYearId" onchange="showYear(this.value);" class="Listmenu70 FloatLft">
                                                <option value="1"><?php echo $year1; ?></option>
                                                <option value="2"><?php echo $year2; ?></option>
                                                <option value="3"><?php echo $year3; ?></option>
                                                <option value="4"><?php echo $year4; ?></option>
                                            </select> 
                                            </span>
                                        </div>
                                        <div class="FloatLft pad-lft10">
                                            <p class="key"><?php echo tranText('key'); ?></p>
                                            <p class="available"><?php echo tranText('available'); ?></p>
                                            <p class="booked"><?php echo tranText('booked'); ?></p>
                                            <p class="unavailable"><?php echo tranText('unknown_unavailable'); ?></p>
                                        </div>
                                    </div>
                                    <!-- THIS DIV IS FOR SHOW YEAR ONE CALENDAR START -->
                                    <div class="calendar-tab" id="calendarsId1" style="margin:0px auto;">
                                        <?php echo $calendarObj->getYearPropertyAvailablityHTML4Holiday($year1, $propertyAvailInfo); ?>
                                    </div>
                                    <!-- THIS DIV IS FOR SHOW YEAR ONE CALENDAR END -->
                                    <!-- THIS DIV IS FOR SHOW YEAR TWO CALENDAR START -->
                                    <div class="calendar-tab" id="calendarsId2" style="display:none; margin:0px auto;">
                                        <?php echo $calendarObj->getYearPropertyAvailablityHTML4Holiday($year2, $propertyAvailInfo); ?>
                                    </div>
                                    <!-- THIS DIV IS FOR SHOW YEAR TWO CALENDAR END -->
                                    <!-- THIS DIV IS FOR SHOW YEAR THREE CALENDAR START -->
                                    <div class="calendar-tab" id="calendarsId3"  style="display:none; margin:0px auto;">
                                        <?php echo $calendarObj->getYearPropertyAvailablityHTML4Holiday($year3, $propertyAvailInfo); ?>
                                    </div>
                                    <!-- THIS DIV IS FOR SHOW YEAR THREE CALENDAR END -->
                                    <!-- THIS DIV IS FOR SHOW YEAR FOUR CALENDAR START -->
                                    <div class="calendar-tab" id="calendarsId4" style="display:none; margin:0px auto;">
                                        <?php echo $calendarObj->getYearPropertyAvailablityHTML4Holiday($year4, $propertyAvailInfo); ?>
                                    </div>
                                    <!-- THIS DIV IS FOR SHOW YEAR FOUR CALENDAR END -->
                                </td>
                                <td valign="top" width="450">
                                <?php if($propertyObj->fun_checkBookingAvailability($property_id) == true) {
										$mindays = (is_array($minStayArr) && !empty($minStayArr))?min($minStayArr):0;
								?>
                                    <div class="pad-lft20 pad-rgt10 bor-h font12">
                                        <div class="gray14 pad-btm10"><?php echo tranText('book_this_property'); ?>...</div>
                                        <div class="pad-btm5"><strong><?php echo tranText('if_you_would_like_to_make_a_provisional_booking_of_this_property_simply_follow_the_3_steps_reservation_process'); ?> ...<br /><?php echo tranText('no_credit_card_details_required'); ?>.</strong></div>
                                        <form name="frmPropertyBooking" id="frmPropertyBooking" method="post" action="<?php echo SITE_URL;?>property-booking-preview.php">
                                        <table width="350" border="0" class="bod-p" cellpadding="0" cellspacing="0">
                                            <tr>
                                                <td class="pad-btm5 pad-rgt5"><img src="<?php echo SITE_IMAGES;?>icon-no1.gif" width="39" alt="one" /></td>
                                                <td colspan="2" valign="middle"><strong><?php echo tranText('check_availability_using_the_big_calendar_on_the_left'); ?></strong></td>
                                            </tr>
                                            <tr>
                                                <td class="pad-btm5 pad-rgt5"><img src="<?php echo SITE_IMAGES;?>icon-no2.gif" width="39" alt="one" /></td>
                                                <td colspan="2" valign="middle"><strong><?php echo tranText('choose_duration_of_stay_from_drop_down_menu_below'); ?>.</strong></td>
                                            </tr>
                                            <tr>
                                                 <td colspan="3"  class="mar pad" align="center">
                                                    <?php $propertyObj->fun_createPropertySelectTripDuration($property_id, "txtDuration", "txtDurationId", "select128", $mindays, "return enabledateChoose()"); ?>
                                                </td>
                                            </tr>
								  <?php /*?>   
                                            <tr>
                                                <td class="pad-btm5 pad-rgt5"><img src="<?php echo SITE_IMAGES;?>icon-no2.gif" width="39" alt="one" /></td>
                                                <td colspan="2" valign="middle"><strong>If this proeprty is not a villa, please choose unit type(s) and No. of unit(s) below:</strong></td>
                                            </tr>
                                            <tr height="5px"><td colspan="3"></td></tr>
                                            <tr>
                                                <td valign="middle" colspan="2">One bdr apts (up to 3 persons)</td>
                                                <td valign="middle"><?php $propertyObj->fun_createSelectNumField("txtOneBdrApt", "txtOneBdrApt", "numbers", '', "", 1, 20); ?></td>
                                            </tr>
                                            <tr height="5px"><td colspan="3"></td></tr>
                                            <tr>
                                                <td valign="middle" colspan="2">Two bdr apts (up to 5 persons)</td>
                                                <td valign="middle"><?php $propertyObj->fun_createSelectNumField("txtTwoBdrApts", "txtTwoBdrApts", "numbers", '', "", 1, 20); ?></td>
                                            </tr>
                                            <tr height="5px"><td colspan="3"></td></tr>
                                            <tr>
                                                <td valign="middle" colspan="2">Three bdr apts (up to 7 persons)</td>
                                                <td valign="middle"><?php $propertyObj->fun_createSelectNumField("txtThreeBdrApts", "txtThreeBdrApts", "numbers", '', "", 1, 20); ?></td>
                                            </tr>
                                            <tr height="5px"><td colspan="3"></td></tr>
                                            <tr>
                                                <td valign="middle" colspan="2">Twin studio (up to 2 persons)</td>
                                                <td valign="middle"><?php $propertyObj->fun_createSelectNumField("txtTwinStudio", "txtTwinStudio", "numbers", '', "", 1, 20); ?></td>
                                            </tr>
                                            <tr height="5px"><td colspan="3"></td></tr>
                                            <tr>
                                                <td valign="middle" colspan="2">Triple studio (up to 3 persons)</td>
                                                <td valign="middle"><?php $propertyObj->fun_createSelectNumField("txtTripleStudio", "txtTripleStudio", "numbers", '', "", 1, 20); ?></td>
                                            </tr>
                                            <tr height="5px"><td colspan="3"></td></tr>
                                            <tr>
                                                <td valign="middle" colspan="2">Room only (up to 2 persons)</td>
                                                <td valign="middle"><?php $propertyObj->fun_createSelectNumField("txtRoomOnly2", "txtRoomOnly2", "numbers", '', "", 1, 20); ?></td>
                                            </tr>
                                            <tr height="5px"><td colspan="3"></td></tr>
                                            <tr>
                                                <td valign="middle" colspan="2">Room only (up to 3 persons)</td>
                                                <td valign="middle"><?php $propertyObj->fun_createSelectNumField("txtRoomOnly3", "txtRoomOnly3", "numbers", '', "", 1, 20); ?></td>
                                            </tr>
                                            <tr height="5px"><td colspan="3"></td></tr>
							<?php */?>
                                            <tr>
                                                <td style="margin:0px;" class="pad-btm5 pad-rgt5"><img src="<?php echo SITE_IMAGES;?>icon-no3.gif" width="39" alt="two" /></td>
                                                <td colspan="2" class="mar pad" valign="middle"><strong>Pick an arrival date from the small calendar below.</strong></td>
                                            </tr>
                                            <tr><td  colspan="3" class="bod-h2"></td><tr>
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td align="right"  style="margin:0px;" valign="middle" width="145px" class="pad-rgt5 pad-top15">
                                                    <span style="font-size:11px; line-height:13px;"><?php echo tranText('click_calendar'); ?> <br /><?php echo tranText('to_choose_your'); ?> <br /><?php echo tranText('key'); ?> -&gt;&gt;</span>
                                                </td>
                                                <td align="left" class="mar pad" valign="middle">
                                                    <div id="txtDateChooserOff" class="date-icon pad-top15" style="display:<?php if((isset($mindays) && $mindays > 0) && ($propertyObj->fun_checkBookingAvailability($property_id) == true)) { echo "none";} else {echo "block";}?>;">
                                                    <img src="<?php echo SITE_IMAGES;?>icon-17-big.jpg" alt="calendar"   />
                                                    </div>
                                                    <div id="txtDateChooserOn" class="date-icon pad-top15" style="display:<?php if((isset($mindays) && $mindays > 0) && ($propertyObj->fun_checkBookingAvailability($property_id) == true)) { echo "block";} else {echo "none";}?>;">
                                                    <a href="javaScript:find_cal4(<?php echo time()?>, '');"><img src="<?php echo SITE_IMAGES;?>icon-17-big.jpg" alt="calendar" /></a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr><td  colspan="3" class="bod-h2"></td><tr>
                                            <tr>
                                                <td colspan="3">
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td height="40" colspan="4" class="green2">Price to pay...</td>
                                                        </tr>
                                                        <tr>
                                                            <td>
                                                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                                    <tr>
                                                                        <td valign="top">
                                                                            <div>
                                                                                <?php
                                                                                $cur_unixtime 	= time();
                                                                                $year 	= date("Y");
                                                                                $month 	= date("m");
                                                                                $day 	= date("d");
                                                                                $datefromArr 	= $propertyObj->fun_getPropertyAvailabilityArr($property_id, $year, $month, $day);
                                                                                // From date
                                                                                $date_from 	= (strtotime($datefromArr[0]['startdate']) > $cur_unixtime)?$datefromArr[0]['startdate']:date("Y-m-d");
                                                                                $date_to 	= date("Y-m-d", (strtotime($date_from)+($mindays*24*60*60)));
                                                                                ?>
                                                                                    <input type="hidden" name="securityKey" value="<?php echo md5(BOOKINGENGINE); ?>" />
                                                                                    <input type="hidden" name="txtPropertyId" id="txtPropertyId" value="<?php echo $property_id; ?>" />
                                                                                    <input type="hidden" name="txtArriavalDate" id="txtArriavalDate" value="<?php echo $date_from; ?>" />
                                                                                    <input type="hidden" name="txtDepartureDate" id="txtDepartureDate" value="<?php echo $date_to; ?>" />
                                                                                <div id="bookNowId">
                                                                                    <?php $propertyObj->fun_createPropertyBookTrip($property_id, $date_from, $date_to, $mindays, $users_currency_code); ?>
                                                                                </div>
                                                                            </div>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                        </form>
                                    </div>
								<?php } else { echo "&nbsp;";} ?>
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <!-- property inner tabs : end here -->
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>
</table>
